// This file is automatically generated. Do not modify it manually.

import { FirebaseOptions, initializeApp, getApp, getApps } from "firebase/app";

/**
 * The Firebase config object for the web app.
 *
 * This is a public, client-safe object that can be exposed in your application.
 * It does not contain any sensitive information.
 * 
 * You can find this object in the Firebase console:
 * Project settings > General > Your apps > Web app > SDK setup and configuration
 */
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyAplLt9Seu6MlCF4Vkzj23knQJHZsiCPVE",
  authDomain: "studio-2974479464-2f7f9.firebaseapp.com",
  projectId: "studio-2974479464-2f7f9",
  storageBucket: "studio-2974479464-2f7f9.appspot.com",
  messagingSenderId: "11484370991",
  appId: "1:11484370991:web:fb7cdb8159b24830650eda"
};

/**
 * Initializes a Firebase app if it hasn't been initialized yet.
 *
 * @returns The initialized Firebase app.
 */
function createFirebaseApp(config: FirebaseOptions) {
  return getApps().length > 0 ? getApp() : initializeApp(config);
}

/**
 * The initialized Firebase app.
 *
 * This is a singleton that can be used throughout the application.
 */
export const firebaseApp = createFirebaseApp(firebaseConfig);
