
// This file is automatically generated. Do not modify it manually.

import { FirebaseOptions, initializeApp, getApp, getApps } from "firebase/app";

/**
 * The Firebase config object for the web app.
 *
 * This is a public, client-safe object that can be exposed in your application.
 * It does not contain any sensitive information.
 * 
 * You can find this object in the Firebase console:
 * Project settings > General > Your apps > Web app > SDK setup and configuration
 */
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyD0PXxekRyA_6aVVkv3q0ZXhh3Ye-eQ4qY",
  authDomain: "alumbra-31c03.firebaseapp.com",
  projectId: "alumbra-31c03",
  storageBucket: "alumbra-31c03.appspot.com",
  messagingSenderId: "1019874127378",
  appId: "1:1019874127378:web:765900067477bd6381f2cb"
};

/**
 * Initializes a Firebase app if it hasn't been initialized yet.
 *
 * @returns The initialized Firebase app.
 */
function createFirebaseApp(config: FirebaseOptions) {
  return getApps().length > 0 ? getApp() : initializeApp(config);
}

/**
 * The initialized Firebase app.
 *
 * This is a singleton that can be used throughout the application.
 */
export const firebaseApp = createFirebaseApp(firebaseConfig);
